# Generated by Django 3.1.7 on 2021-02-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Administrator'), (2, 'User')], default=2, null=True),
        ),
    ]
