# Generated by Django 3.1.7 on 2021-02-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210222_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(True, 'Administrator'), (True, 'User')], default=True, null=True),
        ),
    ]
