# Generated by Django 3.1.7 on 2021-02-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210222_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('ADMIN', 'Administrator'), ('USER', 'User')], default='USER', null=True),
        ),
    ]
