# Generated by Django 3.1.7 on 2021-02-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20210224_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrator'), ('USER', 'User'), ('DEV', 'Developer')], default='USER', max_length=50, null=True),
        ),
    ]
